- 어플 제작 안해봐서 허졉합니다.
- 유튜브 참고해서 만들어서 여러가지 잡기능이 포함되어 있어서 가지치기 해야 합니다. 
- 유튜브 영상을 기준으로 절반 정도 만들었는데, 나머지 부분과 저희가 만드는 기능 통합이나 디자인 등 추가해야합니다
- [참고사이트](https://www.youtube.com/watch?v=RDR22PPWY8E&list=PL4fpXNDGXCyWXY7Sb_bp9VEENEW_UsG75&index=20)
